# Generated by Django 4.0.2 on 2022-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_post_postelement_commentelement_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='sex',
            field=models.CharField(max_length=255),
        ),
    ]
