# Generated by Django 4.0.2 on 2022-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usersettings_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='preposition',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='hard_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='parts_access',
            field=models.CharField(default='1111111', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='work_place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
